# Generated by Django 4.2.3 on 2023-07-05 09:44

from django.db import migrations
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "document",
                        wagtail.documents.blocks.DocumentChooserBlock(
                            label="Document (ancien bloc)",
                            template="blocks/document_internal.html",
                        ),
                    )
                ],
                default="",
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
