# Generated by Django 4.2.3 on 2023-07-05 09:54

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "document_list",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "document_external",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(label="titre"),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.URLBlock(
                                                    label="Lien du document"
                                                ),
                                            ),
                                        ],
                                        label="Document externe",
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        label="Document à télécharger"
                                    ),
                                ),
                            ],
                            label="Document",
                        ),
                    ),
                    (
                        "document",
                        wagtail.documents.blocks.DocumentChooserBlock(
                            label="Document (ancien bloc)",
                            template="blocks/document_internal.html",
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
