# Generated by Django 4.2.3 on 2023-07-05 09:59

from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation

class StreamChildrenToStreamBlockOperationCustom(BaseBlockOperation):
    def __init__(self, block_names, stream_block_name):
        super().__init__()
        self.block_names = block_names
        self.stream_block_name = stream_block_name

    def apply(self, block_value):
        mapped_block_value = []
        stream_value = []

        for child_block in block_value:
            if child_block["type"] in self.block_names:
                stream_value.append(child_block)
            else:
                mapped_block_value.append(child_block)

        # Append the new stream block only if it's not empty
        if stream_value:
            new_stream_block = {"type": self.stream_block_name, "value": stream_value}
            mapped_block_value.append(new_stream_block)

        return mapped_block_value

    @property
    def operation_name_fragment(self):
        return "{}_to_stream_block".format("_".join(self.block_names))

class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_homepage_body"),
    ]

    operations = [
          MigrateStreamData(
            app_name="home",
            model_name="HomePage",
            field_name="body",
            operations_and_block_paths=[
                (
                    StreamChildrenToStreamBlockOperationCustom(["document"], "document_list"),
                    "",
                )
            ],
        ),
    ]


